version: '2.1'
services:
  database:
    image: shichoc/mysqlshop
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  myapp:
    image: shichoc/simpleshopmysql:0.0.1-SNAPSHOT
    container_name: simpleshopapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/simpleshop"
      SPRING_DATASOURCE_PASSWORD: "passwd"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge